name: Deploy Pages

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: |
        npm start &
        mkdir -p docs
        cp -r * docs/
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
        git add .
        git commit -m "Deploy"
        git push origin gh-pages
